# Generated by Django 4.2.3 on 2023-07-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user',
            new_name='sender',
        ),
    ]
